name: Lint OpenAPI Spec

on:
  push:
    branches: [main]
    paths:
      - 'postman/specs/**'
  pull_request:
    branches: [main]
    paths:
      - 'postman/specs/**'

jobs:
  lint-spec:
    name: Lint OpenAPI Spec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Lint OpenAPI Spec
        run: postman api lint f710abd8-5ef3-4895-acfb-0685d97a1a29
